### ISSUE TITLE
tricountourf test failing

### ISSUE THREAD

**Issue by ghost** [oceanmodeling/adcircpy#58]
in the `techreport` branch on 420d3f4, related to #57 

https://github.com/JaimeCalzadaNOAA/adcircpy/runs/2115671220?check_suite_focus=true
```
======================================================================
ERROR: test_make_plot_flat_domain (tests.mesh.test_adcirc_mesh.AdcircMeshTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/adcircpy/adcircpy/tests/mesh/test_adcirc_mesh.py", line 224, in test_make_plot_flat_domain
    h.make_plot()
  File "/home/runner/work/adcircpy/adcircpy/adcircpy/mesh/figures.py", line 87, in decorator
    axes = f(*argv, **kwargs)
  File "/home/runner/work/adcircpy/adcircpy/adcircpy/mesh/mesh.py", line 425, in make_plot
    self.tricontourf(
  File "/home/runner/work/adcircpy/adcircpy/adcircpy/mesh/figures.py", line 87, in decorator
    axes = f(*argv, **kwargs)
  File "/home/runner/work/adcircpy/adcircpy/adcircpy/mesh/base.py", line 192, in tricontourf
    axes.tricontourf(self.triangulation, self.values, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/tri/tricontour.py", line 321, in tricontourf
    return TriContourSet(ax, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/tri/tricontour.py", line 40, in __init__
    ContourSet.__init__(self, ax, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/contour.py", line 816, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/tri/tricontour.py", line 52, in _process_args
    tri, z = self._contour_args(args, kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/tri/tricontour.py", line 107, in _contour_args
    self._process_contour_level_args(args[1:])
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/matplotlib/contour.py", line 1172, in _process_contour_level_args
    raise ValueError("Contour levels must be increasing")
ValueError: Contour levels must be increasing

----------------------------------------------------------------------
Ran 63 tests in 4.008s

FAILED (errors=1)
```

**Comment by ghost** [comment]
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/420d3f4ff9b8c316fcf18b85ea42a4181201c80e/tests/mesh/test_adcirc_mesh.py#L220-L224
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/420d3f4ff9b8c316fcf18b85ea42a4181201c80e/adcircpy/mesh/figures.py#L80-L92
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/420d3f4ff9b8c316fcf18b85ea42a4181201c80e/adcircpy/mesh/mesh.py#L425-L430
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/420d3f4ff9b8c316fcf18b85ea42a4181201c80e/adcircpy/mesh/mesh.py#L79-L90
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/420d3f4ff9b8c316fcf18b85ea42a4181201c80e/adcircpy/mesh/base.py#L188-L193
