### ISSUE TITLE
using local HAMTIDE resource fails to find `Q1` constituent

### ISSUE THREAD

**Issue by ghost** [oceanmodeling/adcircpy#62]
running from `CoupledModelDriver` with ADCIRCpy `v1.0.24`:
```
(coupledmodeldriver)  Zachary.Burnett@hfe08  /scratch2/COASTAL/coastal/save/shared/working/zach
 ➜ python scripts/hera_hsofs_sandy_rewritten_mesh.py
[2021-03-25 12:34:17,149] cplmdldrv INFO    : generating 1 "hera" configuration(s) in "/scratch2/COASTAL/coastal/save/shared/working/zach/hera_hsofs_sandy_rewritten_mesh_20210325T123417"
[2021-03-25 12:34:17,150] cplmdldrv INFO    : opening mesh "/scratch2/COASTAL/coastal/save/shared/models/meshes/hsofs/grid_v1/fort.14"
[2021-03-25 12:36:26,595] cplmdldrv INFO    : wrote NEMS coldstart configuration: nems.configure, config.rc, model_configure
[2021-03-25 12:36:27,141] cplmdldrv INFO    : writing NEMS hotstart configuration: nems.configure, config.rc, model_configure
[2021-03-25 12:36:27,172] cplmdldrv INFO    : rewriting original mesh "/scratch2/COASTAL/coastal/save/shared/models/meshes/hsofs/grid_v1/fort.14"
Traceback (most recent call last):
  File "/scratch2/COASTAL/coastal/save/shared/working/zach/scripts/hera_hsofs_sandy_rewritten_mesh.py", line 76, in <module>
    write_adcirc_configurations(
  File "/scratch2/COASTAL/coastal/save/shared/repositories/CoupledModelDriver/coupledmodeldriver/adcirc.py", line 392, in write_adcirc_configurations
    driver.write(
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/driver.py", line 408, in write
    super().write('coldstart', output_directory / coldstart,
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/fort15.py", line 311, in write
    f.write(self.fort15(runtype))
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/fort15.py", line 90, in fort15
    f.append(self.get_tidal_forcing())
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/fort15.py", line 344, in get_tidal_forcing
    amp, phase = self.tidal_forcing.tidal_dataset(
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/forcing/tides/dataset.py", line 29, in __call__
    return self.get_amplitude(constituent, vertices), \
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/forcing/tides/hamtide.py", line 49, in get_amplitude
    return self._get_interpolation('elevation', 'AMPL', constituent,
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/forcing/tides/hamtide.py", line 125, in _get_interpolation
    dataset = self._get_dataset(variable, constituent)
  File "/scratch2/COASTAL/coastal/save/shared/repositories/adcircpy/adcircpy/forcing/tides/hamtide.py", line 101, in _get_dataset
    self.datasets[variable][constituent]['path'] = path
KeyError: 'Q1'
```

_Originally posted by @zacharyburnettNOAA in https://github.com/noaa-ocs-modeling/CoupledModelDriver/issues/44#issuecomment-806666403_

**Comment by ghost** [comment]
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/driver.py#L407-L409
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/fort15.py#L310-L311
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/fort15.py#L90
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/fort15.py#L344-L345
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/forcing/tides/dataset.py#L18-L30
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/forcing/tides/hamtide.py#L41-L50
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/forcing/tides/hamtide.py#L125
https://github.com/JaimeCalzadaNOAA/adcircpy/blob/261d2514735d6ca9e6781e7c7bafb34c2e32db27/adcircpy/forcing/tides/hamtide.py#L98-L105

**Comment by jreniel** [comment]
This was a bug you introduced when you changed my HAMTIDE implementation. It's been corrected.
